// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject_Code
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod_AddSach - Use 'RecordedMethod_AddSachParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod_AddSach()
        {
            #region Variable Declarations
            WinMenuItem uISáchMenuItem = this.UIFrmMainWindow.UIMenuStrip1MenuBar.UIQuảnlýsáchMenuItem.UISáchMenuItem;
            WinEdit uITxtIDEdit = this.UIFrmQLSachWindow.UITxtIDWindow.UITxtIDEdit;
            WinEdit uITxtTenSachEdit = this.UIFrmQLSachWindow.UITxtTenSachWindow.UITxtTenSachEdit;
            WinEdit uITxtGiaEdit = this.UIFrmQLSachWindow.UITxtGiaWindow.UITxtGiaEdit;
            WinComboBox uICboTacGiaComboBox = this.UIFrmQLSachWindow.UICboTacGiaWindow.UICboTacGiaComboBox;
            WinComboBox uIMãLoạiComboBox = this.UIFrmQLSachWindow.UICboMaLoaiWindow.UIMãLoạiComboBox;
            WinComboBox uINhàXuấtBảnComboBox = this.UIFrmQLSachWindow.UICbNXBWindow.UINhàXuấtBảnComboBox;
            WinEdit uITxtSoLuongEdit = this.UIFrmQLSachWindow.UITxtSoLuongWindow.UITxtSoLuongEdit;
            WinButton uIThêmButton = this.UIFrmQLSachWindow.UIThêmWindow.UIThêmButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Click 'Quản lý sách' -> 'Sách' menu item
            Mouse.Click(uISáchMenuItem, new Point(43, 20));

            // Type 'SH12' in 'txtID' text box
            uITxtIDEdit.Text = this.RecordedMethod_AddSachParams.UITxtIDEditText;

            // Type '{Tab}' in 'txtID' text box
            Keyboard.SendKeys(uITxtIDEdit, this.RecordedMethod_AddSachParams.UITxtIDEditSendKeys, ModifierKeys.None);

            // Type 'sách văn học 10' in 'txtTenSach' text box
            uITxtTenSachEdit.Text = this.RecordedMethod_AddSachParams.UITxtTenSachEditText;

            // Type '{Tab}' in 'txtTenSach' text box
            Keyboard.SendKeys(uITxtTenSachEdit, this.RecordedMethod_AddSachParams.UITxtTenSachEditSendKeys, ModifierKeys.None);

            // Type '50000' in 'txtGia' text box
            uITxtGiaEdit.Text = this.RecordedMethod_AddSachParams.UITxtGiaEditText;

            // Select 'Ngọc Bích' in 'cboTacGia' combo box
            uICboTacGiaComboBox.SelectedItem = this.RecordedMethod_AddSachParams.UICboTacGiaComboBoxSelectedItem;

            // Select 'giáo dục' in 'Mã Loại' combo box
            uIMãLoạiComboBox.SelectedItem = this.RecordedMethod_AddSachParams.UIMãLoạiComboBoxSelectedItem;

            // Select 'Đại học quốc gia' in 'Nhà Xuất Bản' combo box
            uINhàXuấtBảnComboBox.SelectedItem = this.RecordedMethod_AddSachParams.UINhàXuấtBảnComboBoxSelectedItem;

            // Type '20' in 'txtSoLuong' text box
            uITxtSoLuongEdit.Text = this.RecordedMethod_AddSachParams.UITxtSoLuongEditText;

            // Click 'Thêm' button
            Mouse.Click(uIThêmButton, new Point(36, 14));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(53, 14));
        }
        
        /// <summary>
        /// RecordedMethod_AddSachCode - Use 'RecordedMethod_AddSachCodeParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod_AddSachCode()
        {
            #region Variable Declarations
            WinMenuItem uISáchMenuItem = this.UIFrmMainWindow.UIMenuStrip1MenuBar.UIQuảnlýsáchMenuItem.UISáchMenuItem;
            WinEdit uITxtIDEdit = this.UIFrmQLSachWindow.UITxtIDWindow.UITxtIDEdit;
            WinEdit uITxtGiaEdit = this.UIFrmQLSachWindow.UITxtGiaWindow.UITxtGiaEdit;
            WinEdit uITxtTenSachEdit = this.UIFrmQLSachWindow.UITxtTenSachWindow.UITxtTenSachEdit;
            WinComboBox uICboTacGiaComboBox = this.UIFrmQLSachWindow.UICboTacGiaWindow.UICboTacGiaComboBox;
            WinComboBox uIMãLoạiComboBox = this.UIFrmQLSachWindow.UICboMaLoaiWindow.UIMãLoạiComboBox;
            WinComboBox uINhàXuấtBảnComboBox = this.UIFrmQLSachWindow.UICbNXBWindow.UINhàXuấtBảnComboBox;
            WinEdit uITxtSoLuongEdit = this.UIFrmQLSachWindow.UITxtSoLuongWindow.UITxtSoLuongEdit;
            WinButton uIThêmButton = this.UIFrmQLSachWindow.UIThêmWindow.UIThêmButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WinRowHeader uIItemRowHeader = this.UIFrmQLSachWindow.UIDataGridView1Window.UIDataGridViewTable.UIRow3Row.UIItemRowHeader;
            #endregion

            // Click 'Quản lý sách' -> 'Sách' menu item
            Mouse.Click(uISáchMenuItem, new Point(53, 15));

            // Type 'SH12' in 'txtID' text box
            uITxtIDEdit.Text = this.RecordedMethod_AddSachCodeParams.UITxtIDEditText;

            // Type '{Tab}' in 'txtID' text box
            Keyboard.SendKeys(uITxtIDEdit, this.RecordedMethod_AddSachCodeParams.UITxtIDEditSendKeys, ModifierKeys.None);

            // Type '50000' in 'txtGia' text box
            uITxtGiaEdit.Text = this.RecordedMethod_AddSachCodeParams.UITxtGiaEditText;

            // Type 'sách văn học 10' in 'txtTenSach' text box
            uITxtTenSachEdit.Text = this.RecordedMethod_AddSachCodeParams.UITxtTenSachEditText;

            // Select 'Ngọc Bích' in 'cboTacGia' combo box
            uICboTacGiaComboBox.SelectedItem = this.RecordedMethod_AddSachCodeParams.UICboTacGiaComboBoxSelectedItem;

            // Select 'giáo dục' in 'Mã Loại' combo box
            uIMãLoạiComboBox.SelectedItem = this.RecordedMethod_AddSachCodeParams.UIMãLoạiComboBoxSelectedItem;

            // Select 'Đại học quốc gia' in 'Nhà Xuất Bản' combo box
            uINhàXuấtBảnComboBox.SelectedItem = this.RecordedMethod_AddSachCodeParams.UINhàXuấtBảnComboBoxSelectedItem;

            // Type '20' in 'txtSoLuong' text box
            uITxtSoLuongEdit.Text = this.RecordedMethod_AddSachCodeParams.UITxtSoLuongEditText;

            // Click 'Thêm' button
            Mouse.Click(uIThêmButton, new Point(67, 24));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(47, 14));

            // Click row header
            Mouse.Click(uIItemRowHeader, new Point(11, 6));
        }
        
        /// <summary>
        /// RecordedMethod_EditSach - Use 'RecordedMethod_EditSachParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod_EditSach()
        {
            #region Variable Declarations
            WinMenuItem uISáchMenuItem = this.UIFrmMainWindow.UIMenuStrip1MenuBar.UIQuảnlýsáchMenuItem.UISáchMenuItem;
            WinCell uISH12Cell = this.UIFrmQLSachWindow.UIDataGridView1Window.UIDataGridViewTable.UIRow3Row.UISH12Cell;
            WinEdit uITxtTenSachEdit = this.UIFrmQLSachWindow.UITxtTenSachWindow.UITxtTenSachEdit;
            WinEdit uITxtGiaEdit = this.UIFrmQLSachWindow.UITxtGiaWindow.UITxtGiaEdit;
            WinComboBox uICboTacGiaComboBox = this.UIFrmQLSachWindow.UICboTacGiaWindow.UICboTacGiaComboBox;
            WinComboBox uINhàXuấtBảnComboBox = this.UIFrmQLSachWindow.UICbNXBWindow.UINhàXuấtBảnComboBox;
            WinEdit uITxtSoLuongEdit = this.UIFrmQLSachWindow.UITxtSoLuongWindow.UITxtSoLuongEdit;
            WinButton uISửaButton = this.UIFrmQLSachWindow.UISửaWindow.UISửaButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WinCell uISH12Cell1 = this.UIFrmQLSachWindow.UIDataGridView1Window.UIDataGridViewTable.UIRow3Row11.UISH12Cell;
            #endregion

            // Click 'Quản lý sách' -> 'Sách' menu item
            Mouse.Click(uISáchMenuItem, new Point(51, 11));

            // Click 'SH12' cell
            Mouse.Click(uISH12Cell, new Point(58, 12));

            // Type 'sách văn học 12' in 'txtTenSach' text box
            uITxtTenSachEdit.Text = this.RecordedMethod_EditSachParams.UITxtTenSachEditText;

            // Type '60000' in 'txtGia' text box
            uITxtGiaEdit.Text = this.RecordedMethod_EditSachParams.UITxtGiaEditText;

            // Select 'Tenzin Gyatso' in 'cboTacGia' combo box
            uICboTacGiaComboBox.SelectedItem = this.RecordedMethod_EditSachParams.UICboTacGiaComboBoxSelectedItem;

            // Select 'NXB Tài Chính' in 'Nhà Xuất Bản' combo box
            uINhàXuấtBảnComboBox.SelectedItem = this.RecordedMethod_EditSachParams.UINhàXuấtBảnComboBoxSelectedItem;

            // Type '200000' in 'txtSoLuong' text box
            uITxtSoLuongEdit.Text = this.RecordedMethod_EditSachParams.UITxtSoLuongEditText;

            // Click 'Sửa' button
            Mouse.Click(uISửaButton, new Point(24, 17));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(55, 12));

            // Click 'SH12' cell
            Mouse.Click(uISH12Cell1, new Point(55, 13));
        }
        
        /// <summary>
        /// RecordedMethod_FindSach - Use 'RecordedMethod_FindSachParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod_FindSach()
        {
            #region Variable Declarations
            WinMenuItem uISáchMenuItem = this.UIFrmMainWindow.UIMenuStrip1MenuBar.UIQuảnlýsáchMenuItem.UISáchMenuItem;
            WinEdit uITxtTimEdit = this.UIFrmQLSachWindow.UITxtTimWindow.UITxtTimEdit;
            WinButton uITìmKiếmButton = this.UIFrmQLSachWindow.UITìmKiếmWindow.UITìmKiếmButton;
            WinColumnHeader uIGIABANColumnHeader = this.UIFrmQLSachWindow.UIDataGridView1Window.UIDataGridViewTable.UITopRowRow.UIGIABANColumnHeader;
            #endregion

            // Click 'Quản lý sách' -> 'Sách' menu item
            Mouse.Click(uISáchMenuItem, new Point(40, 6));

            // Type 'sách ôn' in 'txtTim' text box
            uITxtTimEdit.Text = this.RecordedMethod_FindSachParams.UITxtTimEditText;

            // Click 'Tìm Kiếm' button
            Mouse.Click(uITìmKiếmButton, new Point(10, 7));

            // Move 'GIABAN' column header
            Mouse.StartDragging(uIGIABANColumnHeader, new Point(1, 15));
            Mouse.StopDragging(uIGIABANColumnHeader, 46, 8);
        }
        
        /// <summary>
        /// RecordedMethod_DeleteSach
        /// </summary>
        public void RecordedMethod_DeleteSach()
        {
            #region Variable Declarations
            WinMenuItem uISáchMenuItem = this.UIFrmMainWindow.UIMenuStrip1MenuBar.UIQuảnlýsáchMenuItem.UISáchMenuItem;
            WinCell uISH12Cell = this.UIFrmQLSachWindow.UIDataGridView1Window.UIDataGridViewTable.UIRow3Row.UISH12Cell;
            WinButton uIXóaButton = this.UIFrmQLSachWindow.UIXóaWindow.UIXóaButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Click 'Quản lý sách' -> 'Sách' menu item
            Mouse.Click(uISáchMenuItem, new Point(50, 17));

            // Click 'SH12' cell
            Mouse.Click(uISH12Cell, new Point(48, 10));

            // Click 'Xóa' button
            Mouse.Click(uIXóaButton, new Point(47, 21));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(28, 17));
        }
        
        /// <summary>
        /// RecordedMethod_DeleteSachCode
        /// </summary>
        public void RecordedMethod_DeleteSachCode()
        {
            #region Variable Declarations
            WinMenuItem uISáchMenuItem = this.UIFrmMainWindow.UIMenuStrip1MenuBar.UIQuảnlýsáchMenuItem.UISáchMenuItem;
            WinCell uISH12Cell = this.UIFrmQLSachWindow.UIDataGridView1Window.UIDataGridViewTable.UIRow3Row11.UISH12Cell;
            WinButton uIXóaButton = this.UIFrmQLSachWindow.UIXóaWindow.UIXóaButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Click 'Quản lý sách' -> 'Sách' menu item
            Mouse.Click(uISáchMenuItem, new Point(59, 15));

            // Click 'SH12' cell
            Mouse.Click(uISH12Cell, new Point(53, 13));

            // Click 'Xóa' button
            Mouse.Click(uIXóaButton, new Point(67, 20));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(44, 10));
        }
        
        #region Properties
        public virtual RecordedMethod_AddSachParams RecordedMethod_AddSachParams
        {
            get
            {
                if ((this.mRecordedMethod_AddSachParams == null))
                {
                    this.mRecordedMethod_AddSachParams = new RecordedMethod_AddSachParams();
                }
                return this.mRecordedMethod_AddSachParams;
            }
        }
        
        public virtual RecordedMethod_AddSachCodeParams RecordedMethod_AddSachCodeParams
        {
            get
            {
                if ((this.mRecordedMethod_AddSachCodeParams == null))
                {
                    this.mRecordedMethod_AddSachCodeParams = new RecordedMethod_AddSachCodeParams();
                }
                return this.mRecordedMethod_AddSachCodeParams;
            }
        }
        
        public virtual RecordedMethod_EditSachParams RecordedMethod_EditSachParams
        {
            get
            {
                if ((this.mRecordedMethod_EditSachParams == null))
                {
                    this.mRecordedMethod_EditSachParams = new RecordedMethod_EditSachParams();
                }
                return this.mRecordedMethod_EditSachParams;
            }
        }
        
        public virtual RecordedMethod_FindSachParams RecordedMethod_FindSachParams
        {
            get
            {
                if ((this.mRecordedMethod_FindSachParams == null))
                {
                    this.mRecordedMethod_FindSachParams = new RecordedMethod_FindSachParams();
                }
                return this.mRecordedMethod_FindSachParams;
            }
        }
        
        public UIFrmQLSachWindow UIFrmQLSachWindow
        {
            get
            {
                if ((this.mUIFrmQLSachWindow == null))
                {
                    this.mUIFrmQLSachWindow = new UIFrmQLSachWindow();
                }
                return this.mUIFrmQLSachWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        
        public UIFrmMainWindow UIFrmMainWindow
        {
            get
            {
                if ((this.mUIFrmMainWindow == null))
                {
                    this.mUIFrmMainWindow = new UIFrmMainWindow();
                }
                return this.mUIFrmMainWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod_AddSachParams mRecordedMethod_AddSachParams;
        
        private RecordedMethod_AddSachCodeParams mRecordedMethod_AddSachCodeParams;
        
        private RecordedMethod_EditSachParams mRecordedMethod_EditSachParams;
        
        private RecordedMethod_FindSachParams mRecordedMethod_FindSachParams;
        
        private UIFrmQLSachWindow mUIFrmQLSachWindow;
        
        private UIOKWindow mUIOKWindow;
        
        private UIFrmMainWindow mUIFrmMainWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod_AddSach'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod_AddSachParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'SH12' in 'txtID' text box
        /// </summary>
        public string UITxtIDEditText = "SH12";
        
        /// <summary>
        /// Type '{Tab}' in 'txtID' text box
        /// </summary>
        public string UITxtIDEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'sách văn học 10' in 'txtTenSach' text box
        /// </summary>
        public string UITxtTenSachEditText = "sách văn học 10";
        
        /// <summary>
        /// Type '{Tab}' in 'txtTenSach' text box
        /// </summary>
        public string UITxtTenSachEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '50000' in 'txtGia' text box
        /// </summary>
        public string UITxtGiaEditText = "50000";
        
        /// <summary>
        /// Select 'Ngọc Bích' in 'cboTacGia' combo box
        /// </summary>
        public string UICboTacGiaComboBoxSelectedItem = "Ngọc Bích";
        
        /// <summary>
        /// Select 'giáo dục' in 'Mã Loại' combo box
        /// </summary>
        public string UIMãLoạiComboBoxSelectedItem = "giáo dục";
        
        /// <summary>
        /// Select 'Đại học quốc gia' in 'Nhà Xuất Bản' combo box
        /// </summary>
        public string UINhàXuấtBảnComboBoxSelectedItem = "Đại học quốc gia";
        
        /// <summary>
        /// Type '20' in 'txtSoLuong' text box
        /// </summary>
        public string UITxtSoLuongEditText = "20";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod_AddSachCode'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod_AddSachCodeParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'SH12' in 'txtID' text box
        /// </summary>
        public string UITxtIDEditText = "SH12";
        
        /// <summary>
        /// Type '{Tab}' in 'txtID' text box
        /// </summary>
        public string UITxtIDEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '50000' in 'txtGia' text box
        /// </summary>
        public string UITxtGiaEditText = "50000";
        
        /// <summary>
        /// Type 'sách văn học 10' in 'txtTenSach' text box
        /// </summary>
        public string UITxtTenSachEditText = "sách văn học 10";
        
        /// <summary>
        /// Select 'Ngọc Bích' in 'cboTacGia' combo box
        /// </summary>
        public string UICboTacGiaComboBoxSelectedItem = "Ngọc Bích";
        
        /// <summary>
        /// Select 'giáo dục' in 'Mã Loại' combo box
        /// </summary>
        public string UIMãLoạiComboBoxSelectedItem = "giáo dục";
        
        /// <summary>
        /// Select 'Đại học quốc gia' in 'Nhà Xuất Bản' combo box
        /// </summary>
        public string UINhàXuấtBảnComboBoxSelectedItem = "Đại học quốc gia";
        
        /// <summary>
        /// Type '20' in 'txtSoLuong' text box
        /// </summary>
        public string UITxtSoLuongEditText = "20";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod_EditSach'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod_EditSachParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'sách văn học 12' in 'txtTenSach' text box
        /// </summary>
        public string UITxtTenSachEditText = "sách văn học 12";
        
        /// <summary>
        /// Type '60000' in 'txtGia' text box
        /// </summary>
        public string UITxtGiaEditText = "60000";
        
        /// <summary>
        /// Select 'Tenzin Gyatso' in 'cboTacGia' combo box
        /// </summary>
        public string UICboTacGiaComboBoxSelectedItem = "Tenzin Gyatso";
        
        /// <summary>
        /// Select 'NXB Tài Chính' in 'Nhà Xuất Bản' combo box
        /// </summary>
        public string UINhàXuấtBảnComboBoxSelectedItem = "NXB Tài Chính";
        
        /// <summary>
        /// Type '200000' in 'txtSoLuong' text box
        /// </summary>
        public string UITxtSoLuongEditText = "200000";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod_FindSach'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod_FindSachParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'sách ôn' in 'txtTim' text box
        /// </summary>
        public string UITxtTimEditText = "sách ôn";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIFrmQLSachWindow : WinWindow
    {
        
        public UIFrmQLSachWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "frmQLSach";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public UITxtIDWindow UITxtIDWindow
        {
            get
            {
                if ((this.mUITxtIDWindow == null))
                {
                    this.mUITxtIDWindow = new UITxtIDWindow(this);
                }
                return this.mUITxtIDWindow;
            }
        }
        
        public UITxtTenSachWindow UITxtTenSachWindow
        {
            get
            {
                if ((this.mUITxtTenSachWindow == null))
                {
                    this.mUITxtTenSachWindow = new UITxtTenSachWindow(this);
                }
                return this.mUITxtTenSachWindow;
            }
        }
        
        public UITxtGiaWindow UITxtGiaWindow
        {
            get
            {
                if ((this.mUITxtGiaWindow == null))
                {
                    this.mUITxtGiaWindow = new UITxtGiaWindow(this);
                }
                return this.mUITxtGiaWindow;
            }
        }
        
        public UICboTacGiaWindow UICboTacGiaWindow
        {
            get
            {
                if ((this.mUICboTacGiaWindow == null))
                {
                    this.mUICboTacGiaWindow = new UICboTacGiaWindow(this);
                }
                return this.mUICboTacGiaWindow;
            }
        }
        
        public UICboMaLoaiWindow UICboMaLoaiWindow
        {
            get
            {
                if ((this.mUICboMaLoaiWindow == null))
                {
                    this.mUICboMaLoaiWindow = new UICboMaLoaiWindow(this);
                }
                return this.mUICboMaLoaiWindow;
            }
        }
        
        public UICbNXBWindow UICbNXBWindow
        {
            get
            {
                if ((this.mUICbNXBWindow == null))
                {
                    this.mUICbNXBWindow = new UICbNXBWindow(this);
                }
                return this.mUICbNXBWindow;
            }
        }
        
        public UITxtSoLuongWindow UITxtSoLuongWindow
        {
            get
            {
                if ((this.mUITxtSoLuongWindow == null))
                {
                    this.mUITxtSoLuongWindow = new UITxtSoLuongWindow(this);
                }
                return this.mUITxtSoLuongWindow;
            }
        }
        
        public UIThêmWindow UIThêmWindow
        {
            get
            {
                if ((this.mUIThêmWindow == null))
                {
                    this.mUIThêmWindow = new UIThêmWindow(this);
                }
                return this.mUIThêmWindow;
            }
        }
        
        public UIDataGridView1Window UIDataGridView1Window
        {
            get
            {
                if ((this.mUIDataGridView1Window == null))
                {
                    this.mUIDataGridView1Window = new UIDataGridView1Window(this);
                }
                return this.mUIDataGridView1Window;
            }
        }
        
        public UISửaWindow UISửaWindow
        {
            get
            {
                if ((this.mUISửaWindow == null))
                {
                    this.mUISửaWindow = new UISửaWindow(this);
                }
                return this.mUISửaWindow;
            }
        }
        
        public UITxtTimWindow UITxtTimWindow
        {
            get
            {
                if ((this.mUITxtTimWindow == null))
                {
                    this.mUITxtTimWindow = new UITxtTimWindow(this);
                }
                return this.mUITxtTimWindow;
            }
        }
        
        public UITìmKiếmWindow UITìmKiếmWindow
        {
            get
            {
                if ((this.mUITìmKiếmWindow == null))
                {
                    this.mUITìmKiếmWindow = new UITìmKiếmWindow(this);
                }
                return this.mUITìmKiếmWindow;
            }
        }
        
        public UIXóaWindow UIXóaWindow
        {
            get
            {
                if ((this.mUIXóaWindow == null))
                {
                    this.mUIXóaWindow = new UIXóaWindow(this);
                }
                return this.mUIXóaWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITxtIDWindow mUITxtIDWindow;
        
        private UITxtTenSachWindow mUITxtTenSachWindow;
        
        private UITxtGiaWindow mUITxtGiaWindow;
        
        private UICboTacGiaWindow mUICboTacGiaWindow;
        
        private UICboMaLoaiWindow mUICboMaLoaiWindow;
        
        private UICbNXBWindow mUICbNXBWindow;
        
        private UITxtSoLuongWindow mUITxtSoLuongWindow;
        
        private UIThêmWindow mUIThêmWindow;
        
        private UIDataGridView1Window mUIDataGridView1Window;
        
        private UISửaWindow mUISửaWindow;
        
        private UITxtTimWindow mUITxtTimWindow;
        
        private UITìmKiếmWindow mUITìmKiếmWindow;
        
        private UIXóaWindow mUIXóaWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtIDWindow : WinWindow
    {
        
        public UITxtIDWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtID";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtIDEdit
        {
            get
            {
                if ((this.mUITxtIDEdit == null))
                {
                    this.mUITxtIDEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtIDEdit.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUITxtIDEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtIDEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtTenSachWindow : WinWindow
    {
        
        public UITxtTenSachWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTenSach";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTenSachEdit
        {
            get
            {
                if ((this.mUITxtTenSachEdit == null))
                {
                    this.mUITxtTenSachEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTenSachEdit.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUITxtTenSachEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTenSachEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtGiaWindow : WinWindow
    {
        
        public UITxtGiaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtGia";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtGiaEdit
        {
            get
            {
                if ((this.mUITxtGiaEdit == null))
                {
                    this.mUITxtGiaEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtGiaEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Tên Sách";
                    this.mUITxtGiaEdit.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUITxtGiaEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtGiaEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UICboTacGiaWindow : WinWindow
    {
        
        public UICboTacGiaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboTacGia";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICboTacGiaComboBox
        {
            get
            {
                if ((this.mUICboTacGiaComboBox == null))
                {
                    this.mUICboTacGiaComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICboTacGiaComboBox.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUICboTacGiaComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICboTacGiaComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UICboMaLoaiWindow : WinWindow
    {
        
        public UICboMaLoaiWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboMaLoai";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIMãLoạiComboBox
        {
            get
            {
                if ((this.mUIMãLoạiComboBox == null))
                {
                    this.mUIMãLoạiComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIMãLoạiComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Mã Loại";
                    this.mUIMãLoạiComboBox.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUIMãLoạiComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIMãLoạiComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UICbNXBWindow : WinWindow
    {
        
        public UICbNXBWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cbNXB";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinComboBox UINhàXuấtBảnComboBox
        {
            get
            {
                if ((this.mUINhàXuấtBảnComboBox == null))
                {
                    this.mUINhàXuấtBảnComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUINhàXuấtBảnComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Nhà Xuất Bản";
                    this.mUINhàXuấtBảnComboBox.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUINhàXuấtBảnComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUINhàXuấtBảnComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtSoLuongWindow : WinWindow
    {
        
        public UITxtSoLuongWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtSoLuong";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtSoLuongEdit
        {
            get
            {
                if ((this.mUITxtSoLuongEdit == null))
                {
                    this.mUITxtSoLuongEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtSoLuongEdit.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUITxtSoLuongEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtSoLuongEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIThêmWindow : WinWindow
    {
        
        public UIThêmWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnThem";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinButton UIThêmButton
        {
            get
            {
                if ((this.mUIThêmButton == null))
                {
                    this.mUIThêmButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIThêmButton.SearchProperties[WinButton.PropertyNames.Name] = "Thêm";
                    this.mUIThêmButton.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUIThêmButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIThêmButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIDataGridView1Window : WinWindow
    {
        
        public UIDataGridView1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "dataGridView1";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public UIDataGridViewTable UIDataGridViewTable
        {
            get
            {
                if ((this.mUIDataGridViewTable == null))
                {
                    this.mUIDataGridViewTable = new UIDataGridViewTable(this);
                }
                return this.mUIDataGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridViewTable mUIDataGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIDataGridViewTable : WinTable
    {
        
        public UIDataGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTable.PropertyNames.Name] = "DataGridView";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public UIRow3Row UIRow3Row
        {
            get
            {
                if ((this.mUIRow3Row == null))
                {
                    this.mUIRow3Row = new UIRow3Row(this);
                }
                return this.mUIRow3Row;
            }
        }
        
        public UIRow3Row1 UIRow3Row1
        {
            get
            {
                if ((this.mUIRow3Row1 == null))
                {
                    this.mUIRow3Row1 = new UIRow3Row1(this);
                }
                return this.mUIRow3Row1;
            }
        }
        
        public UITopRowRow UITopRowRow
        {
            get
            {
                if ((this.mUITopRowRow == null))
                {
                    this.mUITopRowRow = new UITopRowRow(this);
                }
                return this.mUITopRowRow;
            }
        }
        
        public UIRow0Row UIRow0Row
        {
            get
            {
                if ((this.mUIRow0Row == null))
                {
                    this.mUIRow0Row = new UIRow0Row(this);
                }
                return this.mUIRow0Row;
            }
        }
        
        public UIRow0Row1 UIRow0Row1
        {
            get
            {
                if ((this.mUIRow0Row1 == null))
                {
                    this.mUIRow0Row1 = new UIRow0Row1(this);
                }
                return this.mUIRow0Row1;
            }
        }
        
        public UIRow3Row11 UIRow3Row11
        {
            get
            {
                if ((this.mUIRow3Row11 == null))
                {
                    this.mUIRow3Row11 = new UIRow3Row11(this);
                }
                return this.mUIRow3Row11;
            }
        }
        #endregion
        
        #region Fields
        private UIRow3Row mUIRow3Row;
        
        private UIRow3Row1 mUIRow3Row1;
        
        private UITopRowRow mUITopRowRow;
        
        private UIRow0Row mUIRow0Row;
        
        private UIRow0Row1 mUIRow0Row1;
        
        private UIRow3Row11 mUIRow3Row11;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRow3Row : WinRow
    {
        
        public UIRow3Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Value] = "SH12      ;NXB4      ;TG10      ;TL1       ;sách văn học 10;20;50000";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinRowHeader UIItemRowHeader
        {
            get
            {
                if ((this.mUIItemRowHeader == null))
                {
                    this.mUIItemRowHeader = new WinRowHeader(this);
                    #region Search Criteria
                    this.mUIItemRowHeader.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUIItemRowHeader;
            }
        }
        
        public WinCell UINXB4Cell
        {
            get
            {
                if ((this.mUINXB4Cell == null))
                {
                    this.mUINXB4Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUINXB4Cell.SearchProperties[WinCell.PropertyNames.Value] = "NXB4      ";
                    this.mUINXB4Cell.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUINXB4Cell;
            }
        }
        
        public WinCell UITL1Cell
        {
            get
            {
                if ((this.mUITL1Cell == null))
                {
                    this.mUITL1Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUITL1Cell.SearchProperties[WinCell.PropertyNames.Value] = "TL1       ";
                    this.mUITL1Cell.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUITL1Cell;
            }
        }
        
        public WinCell UISH12Cell
        {
            get
            {
                if ((this.mUISH12Cell == null))
                {
                    this.mUISH12Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUISH12Cell.SearchProperties[WinCell.PropertyNames.Value] = "SH12      ";
                    this.mUISH12Cell.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUISH12Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinRowHeader mUIItemRowHeader;
        
        private WinCell mUINXB4Cell;
        
        private WinCell mUITL1Cell;
        
        private WinCell mUISH12Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRow3Row1 : WinRow
    {
        
        public UIRow3Row1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Value] = "SH12      ;NXB8      ;TG2       ;TL1       ;sách văn học 12;50000;50";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinRowHeader UIItemRowHeader
        {
            get
            {
                if ((this.mUIItemRowHeader == null))
                {
                    this.mUIItemRowHeader = new WinRowHeader(this);
                    #region Search Criteria
                    this.mUIItemRowHeader.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUIItemRowHeader;
            }
        }
        #endregion
        
        #region Fields
        private WinRowHeader mUIItemRowHeader;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITopRowRow : WinRow
    {
        
        public UITopRowRow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Name] = "Top Row";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinColumnHeader UIGIABANColumnHeader
        {
            get
            {
                if ((this.mUIGIABANColumnHeader == null))
                {
                    this.mUIGIABANColumnHeader = new WinColumnHeader(this);
                    #region Search Criteria
                    this.mUIGIABANColumnHeader.SearchProperties[WinControl.PropertyNames.Name] = "GIABAN";
                    this.mUIGIABANColumnHeader.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUIGIABANColumnHeader;
            }
        }
        
        public WinColumnHeader UITENSACHColumnHeader
        {
            get
            {
                if ((this.mUITENSACHColumnHeader == null))
                {
                    this.mUITENSACHColumnHeader = new WinColumnHeader(this);
                    #region Search Criteria
                    this.mUITENSACHColumnHeader.SearchProperties[WinControl.PropertyNames.Name] = "TENSACH";
                    this.mUITENSACHColumnHeader.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUITENSACHColumnHeader;
            }
        }
        #endregion
        
        #region Fields
        private WinColumnHeader mUIGIABANColumnHeader;
        
        private WinColumnHeader mUITENSACHColumnHeader;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRow0Row : WinRow
    {
        
        public UIRow0Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Value] = "SH1       ;NXB1      ;TG1       ;TL1       ;sách văn học;15000;50";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinCell UISH1Cell
        {
            get
            {
                if ((this.mUISH1Cell == null))
                {
                    this.mUISH1Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUISH1Cell.SearchProperties[WinCell.PropertyNames.Value] = "SH1       ";
                    this.mUISH1Cell.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUISH1Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUISH1Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRow0Row1 : WinRow
    {
        
        public UIRow0Row1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Value] = "SH1       ;NXB1      ;TG1       ;TL1       ;sách văn học;20000;15000";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinCell UISH1Cell
        {
            get
            {
                if ((this.mUISH1Cell == null))
                {
                    this.mUISH1Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUISH1Cell.SearchProperties[WinCell.PropertyNames.Value] = "SH1       ";
                    this.mUISH1Cell.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUISH1Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUISH1Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRow3Row11 : WinRow
    {
        
        public UIRow3Row11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Value] = "SH12      ;NXB10     ;TG1       ;TL1       ;sách văn học 12;60000;200000";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinCell UISH12Cell
        {
            get
            {
                if ((this.mUISH12Cell == null))
                {
                    this.mUISH12Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUISH12Cell.SearchProperties[WinCell.PropertyNames.Value] = "SH12      ";
                    this.mUISH12Cell.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUISH12Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUISH12Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UISửaWindow : WinWindow
    {
        
        public UISửaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnSua";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinButton UISửaButton
        {
            get
            {
                if ((this.mUISửaButton == null))
                {
                    this.mUISửaButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISửaButton.SearchProperties[WinButton.PropertyNames.Name] = "Sửa";
                    this.mUISửaButton.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUISửaButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISửaButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtTimWindow : WinWindow
    {
        
        public UITxtTimWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTim";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTimEdit
        {
            get
            {
                if ((this.mUITxtTimEdit == null))
                {
                    this.mUITxtTimEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTimEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Tên Sách";
                    this.mUITxtTimEdit.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUITxtTimEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTimEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITìmKiếmWindow : WinWindow
    {
        
        public UITìmKiếmWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnTimKiem";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinButton UITìmKiếmButton
        {
            get
            {
                if ((this.mUITìmKiếmButton == null))
                {
                    this.mUITìmKiếmButton = new WinButton(this);
                    #region Search Criteria
                    this.mUITìmKiếmButton.SearchProperties[WinButton.PropertyNames.Name] = "Tìm Kiếm";
                    this.mUITìmKiếmButton.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUITìmKiếmButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUITìmKiếmButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIXóaWindow : WinWindow
    {
        
        public UIXóaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnXoa";
            this.WindowTitles.Add("frmQLSach");
            #endregion
        }
        
        #region Properties
        public WinButton UIXóaButton
        {
            get
            {
                if ((this.mUIXóaButton == null))
                {
                    this.mUIXóaButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIXóaButton.SearchProperties[WinButton.PropertyNames.Name] = "Xóa";
                    this.mUIXóaButton.WindowTitles.Add("frmQLSach");
                    #endregion
                }
                return this.mUIXóaButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIXóaButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIFrmMainWindow : WinWindow
    {
        
        public UIFrmMainWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "frmMain";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("frmMain");
            #endregion
        }
        
        #region Properties
        public UIMenuStrip1MenuBar UIMenuStrip1MenuBar
        {
            get
            {
                if ((this.mUIMenuStrip1MenuBar == null))
                {
                    this.mUIMenuStrip1MenuBar = new UIMenuStrip1MenuBar(this);
                }
                return this.mUIMenuStrip1MenuBar;
            }
        }
        #endregion
        
        #region Fields
        private UIMenuStrip1MenuBar mUIMenuStrip1MenuBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMenuStrip1MenuBar : WinMenuBar
    {
        
        public UIMenuStrip1MenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "menuStrip1";
            this.WindowTitles.Add("frmMain");
            #endregion
        }
        
        #region Properties
        public UIQuảnlýsáchMenuItem UIQuảnlýsáchMenuItem
        {
            get
            {
                if ((this.mUIQuảnlýsáchMenuItem == null))
                {
                    this.mUIQuảnlýsáchMenuItem = new UIQuảnlýsáchMenuItem(this);
                }
                return this.mUIQuảnlýsáchMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private UIQuảnlýsáchMenuItem mUIQuảnlýsáchMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIQuảnlýsáchMenuItem : WinMenuItem
    {
        
        public UIQuảnlýsáchMenuItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenuItem.PropertyNames.Name] = "Quản lý sách";
            this.WindowTitles.Add("frmMain");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UISáchMenuItem
        {
            get
            {
                if ((this.mUISáchMenuItem == null))
                {
                    this.mUISáchMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUISáchMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Sách";
                    this.mUISáchMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUISáchMenuItem.WindowTitles.Add("frmMain");
                    #endregion
                }
                return this.mUISáchMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUISáchMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "SH12      ";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.tooltips_class32", PropertyExpressionOperator.Contains));
            #endregion
        }
        
        #region Properties
        public WinToolTip UISH12ToolTip
        {
            get
            {
                if ((this.mUISH12ToolTip == null))
                {
                    this.mUISH12ToolTip = new WinToolTip(this);
                    #region Search Criteria
                    this.mUISH12ToolTip.SearchProperties[WinControl.PropertyNames.Name] = "SH12      ";
                    #endregion
                }
                return this.mUISH12ToolTip;
            }
        }
        #endregion
        
        #region Fields
        private WinToolTip mUISH12ToolTip;
        #endregion
    }
}
